server:
  port: 8092
  servlet:
    context-path: /dubbo-client

spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:


dubbo:
  application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: Customer
    id: Customer
  registry:                 #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://192.168.120.131:2181
  protocol:
    name: dubbo
    port: 20880